### ISSUE TITLE
nvcc error

### ISSUE THREAD

**Issue by Char-Aznable** [boostorg/hana#396]
I'm trying to use hana in a CUDA project. I got this compilation error in nvcc (cuda 9.1 + gcc 6.3.0) when compiling the example in hana::map (http://boostorg.github.io/hana/structboost_1_1hana_1_1map.html, right before "Synopsis of associated functions"):

```
/home/aznb/.linuxbrew/include/boost/hana/fwd/optional.hpp(343): error: defaulted default constructor cannot be constexpr because the corresponding implicitly declared default constructor would not be constexpr

/home/aznb/.linuxbrew/include/boost/hana/string.hpp(90): error: expression must have a constant value
          detected during:
            instantiation of "boost::hana::string_detail::prepare_impl" based on template arguments <tmp, 0UL, 1UL, 2UL, 3UL, 4UL, 5UL, 6UL> 
(97): here
            instantiation of "decltype(auto) boost::hana::string_detail::prepare(S) [with S=tmp]" 
testmap.cpp(37): here

/home/aznb/.linuxbrew/include/boost/hana/string.hpp(90): error: expression must have a constant value
          detected during:
            instantiation of "boost::hana::string_detail::prepare_impl" based on template arguments <tmp, 0UL, 1UL, 2UL, 3UL, 4UL, 5UL, 6UL> 
(97): here
            instantiation of "decltype(auto) boost::hana::string_detail::prepare(S) [with S=tmp]" 
testmap.cpp(37): here

/home/aznb/.linuxbrew/include/boost/hana/string.hpp(90): error: expression must have a constant value
          detected during:
            instantiation of "boost::hana::string_detail::prepare_impl" based on template arguments <tmp, 0UL, 1UL, 2UL, 3UL, 4UL, 5UL, 6UL> 
(97): here
            instantiation of "decltype(auto) boost::hana::string_detail::prepare(S) [with S=tmp]" 
testmap.cpp(37): here

/home/aznb/.linuxbrew/include/boost/hana/string.hpp(90): error: expression must have a constant value
          detected during:
            instantiation of "boost::hana::string_detail::prepare_impl" based on template arguments <tmp, 0UL, 1UL, 2UL, 3UL, 4UL, 5UL, 6UL> 
(97): here
            instantiation of "decltype(auto) boost::hana::string_detail::prepare(S) [with S=tmp]" 
testmap.cpp(38): here

/home/aznb/.linuxbrew/include/boost/hana/string.hpp(90): error: expression must have a constant value
          detected during:
            instantiation of "boost::hana::string_detail::prepare_impl" based on template arguments <tmp, 0UL, 1UL, 2UL, 3UL, 4UL, 5UL, 6UL> 
(97): here
            instantiation of "decltype(auto) boost::hana::string_detail::prepare(S) [with S=tmp]" 
testmap.cpp(38): here

/home/aznb/.linuxbrew/include/boost/hana/string.hpp(90): error: expression must have a constant value
          detected during:
            instantiation of "boost::hana::string_detail::prepare_impl" based on template arguments <tmp, 0UL, 1UL, 2UL, 3UL, 4UL, 5UL, 6UL> 
(97): here
            instantiation of "decltype(auto) boost::hana::string_detail::prepare(S) [with S=tmp]" 
testmap.cpp(38): here

/home/aznb/.linuxbrew/include/boost/hana/string.hpp(90): error: expression must have a constant value
          detected during:
            instantiation of "boost::hana::string_detail::prepare_impl" based on template arguments <tmp, 0UL, 1UL, 2UL, 3UL, 4UL, 5UL, 6UL> 
(97): here
            instantiation of "decltype(auto) boost::hana::string_detail::prepare(S) [with S=tmp]" 
testmap.cpp(39): here

/home/aznb/.linuxbrew/include/boost/hana/string.hpp(90): error: expression must have a constant value
          detected during:
            instantiation of "boost::hana::string_detail::prepare_impl" based on template arguments <tmp, 0UL, 1UL, 2UL, 3UL, 4UL, 5UL, 6UL> 
(97): here
            instantiation of "decltype(auto) boost::hana::string_detail::prepare(S) [with S=tmp]" 
testmap.cpp(39): here

/home/aznb/.linuxbrew/include/boost/hana/string.hpp(90): error: expression must have a constant value
          detected during:
            instantiation of "boost::hana::string_detail::prepare_impl" based on template arguments <tmp, 0UL, 1UL, 2UL, 3UL, 4UL, 5UL, 6UL> 
(97): here
            instantiation of "decltype(auto) boost::hana::string_detail::prepare(S) [with S=tmp]" 
testmap.cpp(39): here

/home/aznb/.linuxbrew/include/boost/hana/string.hpp(90): error: expression must have a constant value
          detected during:
            instantiation of "boost::hana::string_detail::prepare_impl" based on template arguments <tmp, 0UL, 1UL, 2UL, 3UL, 4UL, 5UL, 6UL> 
(97): here
            instantiation of "decltype(auto) boost::hana::string_detail::prepare(S) [with S=tmp]" 
testmap.cpp(42): here

/home/aznb/.linuxbrew/include/boost/hana/string.hpp(90): error: expression must have a constant value
          detected during:
            instantiation of "boost::hana::string_detail::prepare_impl" based on template arguments <tmp, 0UL, 1UL, 2UL, 3UL, 4UL, 5UL, 6UL> 
(97): here
            instantiation of "decltype(auto) boost::hana::string_detail::prepare(S) [with S=tmp]" 
testmap.cpp(42): here

/home/aznb/.linuxbrew/include/boost/hana/string.hpp(90): error: expression must have a constant value
          detected during:
            instantiation of "boost::hana::string_detail::prepare_impl" based on template arguments <tmp, 0UL, 1UL, 2UL, 3UL, 4UL, 5UL, 6UL> 
(97): here
            instantiation of "decltype(auto) boost::hana::string_detail::prepare(S) [with S=tmp]" 
testmap.cpp(42): here

/home/aznb/.linuxbrew/include/boost/hana/string.hpp(90): error: expression must have a constant value
          detected during:
            instantiation of "boost::hana::string_detail::prepare_impl" based on template arguments <tmp, 0UL, 1UL, 2UL, 3UL, 4UL, 5UL, 6UL> 
(97): here
            instantiation of "decltype(auto) boost::hana::string_detail::prepare(S) [with S=tmp]" 
testmap.cpp(45): here

/home/aznb/.linuxbrew/include/boost/hana/string.hpp(90): error: expression must have a constant value
          detected during:
            instantiation of "boost::hana::string_detail::prepare_impl" based on template arguments <tmp, 0UL, 1UL, 2UL, 3UL, 4UL, 5UL, 6UL> 
(97): here
            instantiation of "decltype(auto) boost::hana::string_detail::prepare(S) [with S=tmp]" 
testmap.cpp(45): here

/home/aznb/.linuxbrew/include/boost/hana/string.hpp(90): error: expression must have a constant value
          detected during:
            instantiation of "boost::hana::string_detail::prepare_impl" based on template arguments <tmp, 0UL, 1UL, 2UL, 3UL, 4UL, 5UL, 6UL> 
(97): here
            instantiation of "decltype(auto) boost::hana::string_detail::prepare(S) [with S=tmp]" 
testmap.cpp(45): here

/home/aznb/.linuxbrew/include/boost/hana/string.hpp(90): error: expression must have a constant value
          detected during:
            instantiation of "boost::hana::string_detail::prepare_impl" based on template arguments <tmp, 0UL, 1UL, 2UL, 3UL, 4UL, 5UL, 6UL> 
(97): here
            instantiation of "decltype(auto) boost::hana::string_detail::prepare(S) [with S=tmp]" 
testmap.cpp(48): here

/home/aznb/.linuxbrew/include/boost/hana/string.hpp(90): error: expression must have a constant value
          detected during:
            instantiation of "boost::hana::string_detail::prepare_impl" based on template arguments <tmp, 0UL, 1UL, 2UL, 3UL, 4UL, 5UL, 6UL> 
(97): here
            instantiation of "decltype(auto) boost::hana::string_detail::prepare(S) [with S=tmp]" 
testmap.cpp(48): here

/home/aznb/.linuxbrew/include/boost/hana/string.hpp(90): error: expression must have a constant value
          detected during:
            instantiation of "boost::hana::string_detail::prepare_impl" based on template arguments <tmp, 0UL, 1UL, 2UL, 3UL, 4UL, 5UL, 6UL> 
(97): here
            instantiation of "decltype(auto) boost::hana::string_detail::prepare(S) [with S=tmp]" 
testmap.cpp(48): here

/home/aznb/.linuxbrew/include/boost/hana/string.hpp(90): error: expression must have a constant value
          detected during:
            instantiation of "boost::hana::string_detail::prepare_impl" based on template arguments <tmp, 0UL, 1UL, 2UL, 3UL, 4UL, 5UL, 6UL> 
(97): here
            instantiation of "decltype(auto) boost::hana::string_detail::prepare(S) [with S=tmp]" 
testmap.cpp(51): here

/home/aznb/.linuxbrew/include/boost/hana/string.hpp(90): error: expression must have a constant value
          detected during:
            instantiation of "boost::hana::string_detail::prepare_impl" based on template arguments <tmp, 0UL, 1UL, 2UL, 3UL, 4UL, 5UL, 6UL> 
(97): here
            instantiation of "decltype(auto) boost::hana::string_detail::prepare(S) [with S=tmp]" 
testmap.cpp(51): here

/home/aznb/.linuxbrew/include/boost/hana/string.hpp(90): error: expression must have a constant value
          detected during:
            instantiation of "boost::hana::string_detail::prepare_impl" based on template arguments <tmp, 0UL, 1UL, 2UL, 3UL, 4UL, 5UL, 6UL> 
(97): here
            instantiation of "decltype(auto) boost::hana::string_detail::prepare(S) [with S=tmp]" 
testmap.cpp(51): here

/home/aznb/.linuxbrew/include/boost/hana/string.hpp(90): error: expression must have a constant value
          detected during:
            instantiation of "boost::hana::string_detail::prepare_impl" based on template arguments <tmp, 0UL, 1UL, 2UL, 3UL, 4UL, 5UL, 6UL> 
(97): here
            instantiation of "decltype(auto) boost::hana::string_detail::prepare(S) [with S=tmp]" 
testmap.cpp(54): here

/home/aznb/.linuxbrew/include/boost/hana/string.hpp(90): error: expression must have a constant value
          detected during:
            instantiation of "boost::hana::string_detail::prepare_impl" based on template arguments <tmp, 0UL, 1UL, 2UL, 3UL, 4UL, 5UL, 6UL> 
(97): here
            instantiation of "decltype(auto) boost::hana::string_detail::prepare(S) [with S=tmp]" 
testmap.cpp(54): here

/home/aznb/.linuxbrew/include/boost/hana/string.hpp(90): error: expression must have a constant value
          detected during:
            instantiation of "boost::hana::string_detail::prepare_impl" based on template arguments <tmp, 0UL, 1UL, 2UL, 3UL, 4UL, 5UL, 6UL> 
(97): here
            instantiation of "decltype(auto) boost::hana::string_detail::prepare(S) [with S=tmp]" 
testmap.cpp(54): here

/home/aznb/.linuxbrew/include/boost/hana/string.hpp(90): error: expression must have a constant value
          detected during:
            instantiation of "boost::hana::string_detail::prepare_impl" based on template arguments <tmp, 0UL, 1UL, 2UL, 3UL, 4UL, 5UL, 6UL> 
(97): here
            instantiation of "decltype(auto) boost::hana::string_detail::prepare(S) [with S=tmp]" 
testmap.cpp(55): here

/home/aznb/.linuxbrew/include/boost/hana/string.hpp(90): error: expression must have a constant value
          detected during:
            instantiation of "boost::hana::string_detail::prepare_impl" based on template arguments <tmp, 0UL, 1UL, 2UL, 3UL, 4UL, 5UL, 6UL> 
(97): here
            instantiation of "decltype(auto) boost::hana::string_detail::prepare(S) [with S=tmp]" 
testmap.cpp(55): here

/home/aznb/.linuxbrew/include/boost/hana/string.hpp(90): error: expression must have a constant value
          detected during:
            instantiation of "boost::hana::string_detail::prepare_impl" based on template arguments <tmp, 0UL, 1UL, 2UL, 3UL, 4UL, 5UL, 6UL> 
(97): here
            instantiation of "decltype(auto) boost::hana::string_detail::prepare(S) [with S=tmp]" 
testmap.cpp(55): here

/home/aznb/.linuxbrew/include/boost/hana/string.hpp(90): error: expression must have a constant value
          detected during:
            instantiation of "boost::hana::string_detail::prepare_impl" based on template arguments <tmp, 0UL, 1UL, 2UL, 3UL, 4UL, 5UL, 6UL> 
(97): here
            instantiation of "decltype(auto) boost::hana::string_detail::prepare(S) [with S=tmp]" 
testmap.cpp(56): here

/home/aznb/.linuxbrew/include/boost/hana/string.hpp(90): error: expression must have a constant value
          detected during:
            instantiation of "boost::hana::string_detail::prepare_impl" based on template arguments <tmp, 0UL, 1UL, 2UL, 3UL, 4UL, 5UL, 6UL> 
(97): here
            instantiation of "decltype(auto) boost::hana::string_detail::prepare(S) [with S=tmp]" 
testmap.cpp(56): here

/home/aznb/.linuxbrew/include/boost/hana/string.hpp(90): error: expression must have a constant value
          detected during:
            instantiation of "boost::hana::string_detail::prepare_impl" based on template arguments <tmp, 0UL, 1UL, 2UL, 3UL, 4UL, 5UL, 6UL> 
(97): here
            instantiation of "decltype(auto) boost::hana::string_detail::prepare(S) [with S=tmp]" 
testmap.cpp(56): here

31 errors detected in the compilation of "/home/aznb/tmp/tmpxft_0002f4bb_00000000-8_testmap.cpp1.ii".
```
This looks like a nvcc bug but can someone confirm this? What should I report to Nvidia in order to get their attention to this? Too bad I can't use this library for my project...

Here's the source code and the command line in order to reproduce the error:
```
#include <boost/hana/assert.hpp>
#include <boost/hana/at_key.hpp>
#include <boost/hana/contains.hpp>
#include <boost/hana/map.hpp>
#include <boost/hana/pair.hpp>
#include <boost/hana/string.hpp>
#include <functional>
#include <string>
#include <vector>
namespace hana = boost::hana;
template <typename ...Events>
struct event_system {
    using Callback = std::function<void()>;
    hana::map<hana::pair<Events, std::vector<Callback>>...> map_;
    template <typename Event, typename F>
    void on(Event e, F handler) {
        auto is_known_event = hana::contains(map_, e);
        static_assert(is_known_event,
            "trying to add a handler to an unknown event");
        map_[e].push_back(handler);
    }
    template <typename Event>
    void trigger(Event e) const {
        auto is_known_event = hana::contains(map_, e);
        static_assert(is_known_event,
            "trying to trigger an unknown event");
        for (auto& handler : this->map_[e])
            handler();
    }
};
template <typename ...Events>
event_system<Events...> make_event_system(Events ...events) {
    return {};
}
int main() {
    auto events = make_event_system(
        BOOST_HANA_STRING("foo"),
        BOOST_HANA_STRING("bar"),
        BOOST_HANA_STRING("baz")
    );
    std::vector<std::string> triggered_events;
    events.on(BOOST_HANA_STRING("foo"), [&] {
        triggered_events.push_back("foo:1");
    });
    events.on(BOOST_HANA_STRING("foo"), [&] {
        triggered_events.push_back("foo:2");
    });
    events.on(BOOST_HANA_STRING("bar"), [&] {
        triggered_events.push_back("bar:1");
    });
    events.on(BOOST_HANA_STRING("baz"), [&] {
        triggered_events.push_back("baz:1");
    });
    events.trigger(BOOST_HANA_STRING("foo"));
    events.trigger(BOOST_HANA_STRING("bar"));
    events.trigger(BOOST_HANA_STRING("baz"));
    BOOST_HANA_RUNTIME_CHECK(triggered_events == std::vector<std::string>{
        "foo:1", "foo:2", "bar:1", "baz:1"
    });
}
```
```
nvcc -x cu testmap.cpp -o testmap -std=c++14
```
Note that the error doesn't happen if `-x cu` option is removed.

**Comment by ricejasonf** [comment]
Your code does not compile on clang either. Just skimming through your error output the problem appears to be with how the `BOOST_HANA_STRING` macro is using a constexpr array or something.

The error that I am getting is caused by your declaring a map type:
```cpp
hana::map<hana::pair<Events, std::vector<Callback>>...> map_;
```
Not only does this result in too many template arguments, but Boost.Hana makes no guarantee about the template parameters in the `hana::map` template. You have to use `hana::make_map`.

While the documentation does state this:
"`Note that the actual representation of a hana::map is an implementation detail.`"

It does appear to be clear in the type signature located above that which should probably be changed to something like:
**template<...>
struct boost::hana::map;**

**Comment by ricejasonf** [comment]
I'm saying that the example is incorrect and does not even compile on Clang.

I'm not sure why yours would work at all.

I'm not sure if I will have time to play with this, but it is kind of related to a presentation I am giving at C++Now next week on compiling C++ programs in Docker.

https://hub.docker.com/r/nvidia/cuda/ <-- Is that the toolchain you are using?

**Comment by Char-Aznable** [comment]
This example does compile with gcc 6.3.0 on my machine. The cuda 9.1 is the tool chain I'm using. The exact version is:
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Nov__3_21:07:56_CDT_2017
Cuda compilation tools, release 9.1, V9.1.85
```

**Comment by Char-Aznable** [comment]
Also, doesn't the first line in the error message look like a compiler bug assuming that hana's definition of constexpr function meets the c++14 requirement?
```
/home/aznb/.linuxbrew/include/boost/hana/fwd/optional.hpp(343): error: defaulted default constructor cannot be constexpr because the corresponding implicitly declared default constructor would not be constexpr
```
What is the error you've seen on Clang?

**Comment by ricejasonf** [comment]
I am mistaken. I must be on a really old version of Boost.Hana.

```
commit e3e8736aabd89c614bb26757eb31627e5c03fdb3
Author: Louis Dionne <ldionne.2@gmail.com>
Date:   Mon Nov 14 17:52:44 2016 -0800

    [map] Allow declaring maps using map<Pairs...>, and provide a variadic constructor
```

**Comment by ldionne** [comment]
I don't have access to NVCC and it's not currently a supported compiler. I can't make any guarantees about it, unfortunately. Your example appears to be correct, though, so it's either a bug in Hana or a bug in the compiler.

Have you tried building Hana's tests and examples? How many failures do you get? If you get a lot of unrelated failures, it may just be that NVCC is not sufficiently standards conforming to support Hana.

**Comment by ldionne** [comment]
Closing since NVCC is not a supported compiler.
